dist: xenial
language: python
services:
- postgresql
- redis-server
- docker
python:
- '3.7'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
before_install:
- docker --version
- docker build -t bilgrami/pakguru:latest .
- docker run -d -p 127.0.0.1:80:5000 bilgrami/pakguru:latest /bin/sh -c "cd
  /opt/startup; ./init_container.sh;"
- docker ps -a
script: cd ./project/pakguru_project/ && python manage.py test;
