FROM python:3.7-slim

LABEL Name=python_base maintainer="Syed Bilgrami <bilgrami@gmail.com>"

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Reference: Best practices for writing Dockerfiles
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

RUN \
 apt-get update && \
 apt-get install -qy --no-install-recommends \
  python3 python3-virtualenv pypy \
  libpq-dev python-dev gcc

RUN pip install virtualenv
