version: '3.7'

services:
  db:
    image: postgres
    env_file: ./config/db.env
    volumes:
      - postgres:/var/lib/postgresql/data
    
  web:
    image: bilgrami/pakguru:latest
    env_file: ./config/web.env
    volumes:
      - ${HOST_PROJECT_FOLDER}:${TARGET_PROJECT_FOLDER}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${iPYTHON_NOTEBOOK_PORT}:${iPYTHON_NOTEBOOK_PORT}"
    depends_on:
       - db

  # redis:
  #   image: "redis:alpine"
volumes:
  postgres:
