curl -s https://pak.guru/comedyshows/
curl -s https://pak.guru/talkshows/
curl -s https://pak.guru/recentshows/
curl -s https://pak.guru/dramaserials/
curl -s https://pak.guru/talkshows/24-news/24-news-khara-sach/22/
curl -s https://pak.guru/talkshows/24-news/24-news-nasim-zehra-800/28/
curl -s https://pak.guru/talkshows/92-news/92-news-hard-talk-pakistan/17/
curl -s https://pak.guru/talkshows/92-news/92-news-ho-kya-raha-hai/35/
curl -s https://pak.guru/talkshows/92-news/92-news-muqabil/7/
curl -s https://pak.guru/talkshows/92-news/92-news-night-edition/13/
curl -s https://pak.guru/talkshows/aaj-news/aaj-news-aaj-rana-mubashir-kay-saath/34/
curl -s https://pak.guru/talkshows/aap-news/aap-news-aap-kay-muqabil/10/
curl -s https://pak.guru/talkshows/aaj-news/aaj-news-faisla-aap-ka/24/
curl -s https://pak.guru/talkshows/abb-takk/abb-takk-tonight-with-fareeha/49/
curl -s https://pak.guru/talkshows/ary-news/ary-news-off-the-record/8/
curl -s https://pak.guru/talkshows/ary-news/ary-news-power-play/18/
curl -s https://pak.guru/talkshows/ary-news/ary-news-sawal-yeh-hai/40/
curl -s https://pak.guru/talkshows/bol-news/bol-news-tajzia-sami-ibrahim-kay-sath/31/
curl -s https://pak.guru/talkshows/dawn-news/dawn-news-news-eye/26/
curl -s https://pak.guru/talkshows/dawn-news/dawn-news-zara-hat-kay/2/
curl -s https://pak.guru/talkshows/dunya-news/dunya-news-dunya-kamran-khan-kay-sath/9/
curl -s https://pak.guru/talkshows/dunya-news/dunya-news-ikhtilafi-note/38/
curl -s https://pak.guru/talkshows/dunya-news/dunya-news-nuqta-e-nazar/36/
curl -s https://pak.guru/talkshows/dunya-news/dunya-news-nuqta-e-nazar/36/
curl -s https://pak.guru/talkshows/dunya-news/dunya-news-on-the-front/37/
curl -s https://pak.guru/talkshows/dunya-news/dunya-news-think-tank/20/
curl -s https://pak.guru/talkshows/express-news/express-news-kal-tak-with-javed-chaudhry/23/
curl -s https://pak.guru/talkshows/express-news/express-news-to-the-point/25/
curl -s https://pak.guru/talkshows/geo-news/geo-news-aaj-shahzaib-khanzada-ke-saath/12/
curl -s https://pak.guru/talkshows/geo-news/geo-news-aapas-ki-baat/44/
curl -s https://pak.guru/talkshows/geo-news/geo-news-capital-talk/16/
curl -s https://pak.guru/talkshows/geo-news/geo-news-jirga/14/
curl -s https://pak.guru/talkshows/geo-news/geo-news-meray-mutabiq-with-hassan-nisar/3/
curl -s https://pak.guru/talkshows/geo-news/geo-news-naya-pakistan/43/
curl -s https://pak.guru/talkshows/geo-news/geo-news-report-card/41/
curl -s https://pak.guru/talkshows/gnn/gnn-face-to-face-with-ayesha-bakhsh/30/
curl -s https://pak.guru/talkshows/gnn/gnn-live-with-dr-shahid-masood/4/
curl -s https://pak.guru/talkshows/hum-tv/hum-tv-breaking-point-with-malick/29/
curl -s https://pak.guru/talkshows/neo-news/neo-news-harf-e-raaz/21/
curl -s https://pak.guru/talkshows/neo-news/neo-news-seedhi-baat/39/
curl -s https://pak.guru/talkshows/samaa-tv/samaa-tv-nadeem-malik-live/33/
curl -s https://pak.guru/talkshows/samaa-tv/samaa-tv-news-beat/32/
curl -s https://pak.guru/comedyshow/ary-digital/ary-digital-bulbulay/47/
curl -s https://pak.guru/comedyshow/dunya-news/dunya-news-hasb-e-haal/51/
curl -s https://pak.guru/comedyshow/dunya-news/dunya-news-mazaaq-raat/52/
curl -s https://pak.guru/comedyshow/express-news/express-news-khabardar/56/
curl -s https://pak.guru/comedyshow/express-news/express-news-syasi-theater/54/
curl -s https://pak.guru/comedyshow/geo-news/geo-news-khabarnak/55/
curl -s https://pak.guru/dramaserial/aplus/aplus-pinjra/68/
curl -s https://pak.guru/dramaserial/geo-tv/geo-tv-khan/57/
curl -s https://pak.guru/dramaserial/geo-tv/geo-tv-sawera/45/
curl -s https://pak.guru/dramaserial/hum-tv/hum-tv-alif-allah-aur-insaan/46/
curl -s https://pak.guru/dramaserial/hum-tv/hum-tv-mah-e-tamaam/50/
curl -s https://pak.guru/dramaserial/hum-tv/hum-tv-naseebon-jali/60/
curl -s https://pak.guru/dramaserial/hum-tv/hum-tv-zindagi-gulzar-hai/62/
curl -s https://pak.guru/dramaserial/tv-one/tv-one-dil-e-majboor/48/
