# Generated by Django 2.2.2 on 2019-06-30 08:15

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Country Name')),
                ('short_name', models.CharField(max_length=10, verbose_name='Short Name')),
                ('capital_city', models.CharField(max_length=100, verbose_name='Capital')),
                ('country_phone_code', models.CharField(max_length=10, verbose_name='country_phone_code')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='LocaleList',
            fields=[
                ('locale_id', models.AutoField(primary_key=True, serialize=False)),
                ('locale_code', models.CharField(default='en-US', max_length=6)),
                ('language', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='PostCategoryList',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.CreateModel(
            name='YouTubeFeed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=300, verbose_name='Show Name')),
                ('feed_name', models.CharField(max_length=300, verbose_name='Show Name')),
                ('channel_short_code', models.CharField(max_length=10, verbose_name='Channel Code')),
                ('channel_name', models.CharField(max_length=300, verbose_name='Channel Name')),
                ('channel_link', models.URLField(max_length=500, verbose_name='Channel Link')),
                ('playlist_link', models.URLField(max_length=500, verbose_name='Playlist Link')),
                ('latest_show_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Latest Show Link')),
                ('search_pattern', models.CharField(blank=True, max_length=500, null=True, verbose_name='Search Pattern')),
                ('search_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Search URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('feed_quality', models.CharField(max_length=50, verbose_name='Feed Quality')),
                ('priority', models.SmallIntegerField(verbose_name='Priority')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_youtube_feeds', to=settings.AUTH_USER_MODEL)),
                ('country', models.ManyToManyField(blank=True, null=True, to='pakguru_app.CountryList')),
            ],
            options={
                'verbose_name_plural': 'Youtube Feeds',
            },
        ),
        migrations.CreateModel(
            name='YouTubeShow',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=300, verbose_name='Show Name')),
                ('host_name', models.CharField(max_length=300, verbose_name='Host Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('channel_short_code', models.CharField(max_length=10, verbose_name='Channel Code')),
                ('channel_name', models.CharField(max_length=300, verbose_name='Channel Name')),
                ('channel_link', models.URLField(max_length=500, verbose_name='Channel Link')),
                ('playlist_link', models.URLField(max_length=500, verbose_name='Playlist Link')),
                ('latest_show_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Latest Show Link')),
                ('search_pattern', models.CharField(blank=True, max_length=500, null=True, verbose_name='Search Pattern')),
                ('search_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Search URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('feed_quality', models.CharField(max_length=50, verbose_name='Feed Quality')),
                ('priority', models.SmallIntegerField(verbose_name='Priority')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_youtube_shows', to=settings.AUTH_USER_MODEL)),
                ('country', models.ManyToManyField(blank=True, null=True, to='pakguru_app.CountryList')),
                ('youtube_feed_list', models.ManyToManyField(related_name='youtube_shows', to='pakguru_app.YouTubeFeed')),
            ],
            options={
                'verbose_name_plural': 'Youtube Shows',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Post Id')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='URL Slug')),
                ('text', models.TextField(verbose_name='Text')),
                ('post_author', models.CharField(max_length=255, verbose_name='Author')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('source_detail', models.TextField(verbose_name='Source Detail')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('embedded video', 'embedded video'), ('document', 'Document')], default='text', max_length=50, verbose_name='Media Type')),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('weekday_name', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3, verbose_name='Weekday')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Tags'), size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created On')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to='pakguru_app.PostCategoryList')),
                ('country', models.ManyToManyField(blank=True, null=True, to='pakguru_app.CountryList')),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pakguru_app.LocaleList')),
                ('youtube_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pakguru_app.YouTubeShow')),
            ],
            managers=[
                ('daily_tv', django.db.models.manager.Manager()),
            ],
        ),
    ]
