# Generated by Django 2.2.2 on 2019-06-25 05:36

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocaleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_code', models.CharField(default='en-US', max_length=6)),
                ('language', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategoryList',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Category Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Category',
            },
        ),
        migrations.CreateModel(
            name='YouTubeFeeds',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=300, verbose_name='Show Name')),
                ('host_name', models.CharField(max_length=300, verbose_name='Host Name')),
                ('channel_short_code', models.CharField(max_length=10, verbose_name='Channel Code')),
                ('channel_name', models.CharField(max_length=300, verbose_name='Channel Name')),
                ('channel_link', models.URLField(max_length=500, verbose_name='Channel Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_youtube_feeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Post Id')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='URL Slug')),
                ('text', models.TextField(verbose_name='Text')),
                ('post_author', models.CharField(max_length=255, verbose_name='Author')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('source_detail', models.TextField(verbose_name='Source Detail')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('embedded video', 'embedded video'), ('document', 'Document')], default='text', max_length=50, verbose_name='Media Type')),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('weekday_name', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3, verbose_name='Weekday')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Tags'), size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created On')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to='pakguru_app.PostCategoryList')),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pakguru_app.LocaleList')),
                ('youtube_feed_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pakguru_app.YouTubeFeeds')),
            ],
        ),
    ]
