# Generated by Django 2.2.2 on 2019-06-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
