# Generated by Django 2.2.2 on 2019-06-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubefeeds',
            name='latest_show_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Latest Show Link'),
        ),
        migrations.AddField(
            model_name='youtubefeeds',
            name='search_pattern',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Search Pattern'),
        ),
        migrations.AddField(
            model_name='youtubefeeds',
            name='search_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Search URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
