# Generated by Django 2.2.2 on 2019-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsourcefeed',
            name='feed_source',
            field=models.CharField(blank=True, choices=[('Youtube', 'Youtube'), ('Talk Shows Central', 'Talk Shows Central'), ('unewstv', 'unewstv'), ('Facebook', 'Facebook'), ('Podcast', 'Podcast'), ('Vimeo', 'Vimeo'), ('Twitter', 'Twitter'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Feed Source'),
        ),
    ]
