# Generated by Django 2.2.3 on 2019-07-03 05:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showfeed_harvestjoblog',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
