# Generated by Django 2.2.3 on 2019-07-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0002_auto_20190701_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PODCAST', 'Podcast'), ('EMBEDDED_VIDEO', 'embedded video'), ('DOCUMENT', 'Document')], default='text', max_length=50, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='weekday_name',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3, verbose_name='Weekday'),
        ),
        migrations.AlterField(
            model_name='show',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Show Name'),
        ),
        migrations.AlterField(
            model_name='show',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='showchannel',
            name='channel_short_code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Channel Code'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='country',
            field=models.ManyToManyField(blank=True, db_index=True, to='pakguru_app.CountryList'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='feed_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Feed Name'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='feed_source',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'Youtube'), ('TALK_SHOWS_CENTRAL', 'Talk Shows Central'), ('UNEWSTV', 'unewstv'), ('FACEBOOK', 'Facebook'), ('PODCAST', 'Podcast'), ('VIMEO', 'Vimeo'), ('TWITTER', 'Twitter'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Feed Source'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='show_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Show Name'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='ShowFeed_HarvestJobLog',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('latest_feed_date', models.DateField(db_index=True, verbose_name='Latest Feed Date')),
                ('is_latest', models.BooleanField(db_index=True, default=True, verbose_name='Is Latest')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pakguru_app.ShowSourceFeed')),
            ],
        ),
    ]
