# Generated by Django 2.2.2 on 2019-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0002_auto_20190630_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeshow',
            name='airtime',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Air Time'),
        ),
        migrations.AddField(
            model_name='youtubeshow',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='youtubeshow',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='youtubeshow',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='country_phone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Phone Code'),
        ),
        migrations.AlterField(
            model_name='youtubeshow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='youtubeshow',
            name='feed_quality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Feed Quality'),
        ),
        migrations.AlterField(
            model_name='youtubeshow',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='youtubeshow',
            name='youtube_feed_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='youtube_shows', to='pakguru_app.YouTubeFeed'),
        ),
    ]
