# Generated by Django 2.2.2 on 2019-06-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0002_auto_20190624_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localelist',
            options={'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='postcategorylist',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterModelOptions(
            name='youtubefeeds',
            options={'verbose_name_plural': 'Youtube Feeds'},
        ),
    ]
