# Generated by Django 2.2.3 on 2019-07-04 04:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pakguru_app', '0003_auto_20190702_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Shows'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_name',
        ),
        migrations.RemoveField(
            model_name='showchannel',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='showsourcefeed',
            name='feed_name',
        ),
        migrations.AddField(
            model_name='author',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_author_related', related_query_name='pakguru_app_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='author',
            name='effective_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='author',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='author',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_countrylist_related', related_query_name='pakguru_app_countrylists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='effective_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='effective_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='postcategorylist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_postcategorylist_related', related_query_name='pakguru_app_postcategorylists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcategorylist',
            name='effective_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='postcategorylist',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='postcategorylist',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcategorylist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='show',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='showchannel',
            name='effective_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='showchannel',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='showchannel',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showchannel',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='showfeed_harvestjoblog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='showfeed_harvestjoblog',
            name='effective_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='showfeed_harvestjoblog',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='showfeed_harvestjoblog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='showfeed_harvestjoblog',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='showsourcefeed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='showsourcefeed',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_post_related', related_query_name='pakguru_app_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='F?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='flagged_data',
            field=models.TextField(blank=True, null=True, verbose_name='Flag Info'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Joke',
            field=models.BooleanField(default=False, verbose_name='J'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Politics',
            field=models.BooleanField(default=False, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Quote',
            field=models.BooleanField(default=False, verbose_name='Q'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Show',
            field=models.BooleanField(default=True, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='postcategorylist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postcategorylist',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='show',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_show_related', related_query_name='pakguru_app_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='show',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='pakguru_app_show_related', related_query_name='pakguru_app_shows', to='pakguru_app.CountryList'),
        ),
        migrations.AlterField(
            model_name='show',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='show',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='website_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='showchannel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_showchannel_related', related_query_name='pakguru_app_showchannels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='showchannel',
            name='country',
        ),
        migrations.AddField(
            model_name='showchannel',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='pakguru_app_showchannel_related', related_query_name='pakguru_app_showchannels', to='pakguru_app.CountryList'),
        ),
        migrations.AlterField(
            model_name='showchannel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showchannel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='showfeed_harvestjoblog',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_showfeed_harvestjoblog_related', related_query_name='pakguru_app_showfeed_harvestjoblogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='showfeed_harvestjoblog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showfeed_harvestjoblog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_showsourcefeed_related', related_query_name='pakguru_app_showsourcefeeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='feed_source',
            field=models.CharField(choices=[('YOUTUBE', 'Youtube'), ('TALK_SHOWS_CENTRAL', 'Talk Shows Central'), ('UNEWSTV', 'unewstv'), ('FACEBOOK', 'Facebook'), ('PODCAST', 'Podcast'), ('VIMEO', 'Vimeo'), ('TWITTER', 'Twitter'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Feed Source'),
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='author',
            table='pakguru_app_author',
        ),
        migrations.AlterModelTable(
            name='countrylist',
            table='pakguru_app_countrylist',
        ),
        migrations.AlterModelTable(
            name='post',
            table='pakguru_app_post',
        ),
        migrations.AlterModelTable(
            name='postcategorylist',
            table='pakguru_app_postcategorylist',
        ),
        migrations.AlterModelTable(
            name='show',
            table='pakguru_app_show',
        ),
        migrations.AlterModelTable(
            name='showchannel',
            table='pakguru_app_showchannel',
        ),
        migrations.AlterModelTable(
            name='showfeed_harvestjoblog',
            table='pakguru_app_showfeed_harvestjoblog',
        ),
        migrations.AlterModelTable(
            name='showsourcefeed',
            table='pakguru_app_showsourcefeed',
        ),
    ]
