# Generated by Django 2.2.2 on 2019-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0003_auto_20190624_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubefeeds',
            name='search_pattern',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Search Pattern'),
        ),
    ]
