# Generated by Django 2.2.3 on 2019-07-06 09:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pakguru_app', '0004_auto_20190703_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='showsourcefeed',
            name='feed_source',
            field=models.CharField(choices=[('YOUTUBE', 'Youtube'), ('TALK_SHOWS_CENTRAL', 'Talk Shows Central'), ('UNEWSTV', 'unewstv'), ('DOL', 'Dramas Online PK'), ('VPK', 'VIDPK'), ('FACEBOOK', 'Facebook'), ('PODCAST', 'Podcast'), ('VIMEO', 'Vimeo'), ('TWITTER', 'Twitter'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Feed Source'),
        ),
        migrations.CreateModel(
            name='FeedSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('effective_date', models.DateTimeField(auto_now=True, verbose_name='Effective Date')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('short_code', models.CharField(db_index=True, max_length=3, verbose_name='Short Code')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakguru_app_feedsourcetype_related', related_query_name='pakguru_app_feedsourcetypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed Source Type',
                'verbose_name_plural': 'Feed Source Types',
                'db_table': 'pakguru_app_feedsourcetype',
            },
        ),
        migrations.AddField(
            model_name='showsourcefeed',
            name='feed_source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pakguru_app.FeedSourceType'),
        ),
    ]
