# Generated by Django 2.2.2 on 2019-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0004_auto_20190624_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubefeeds',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
