# Generated by Django 2.2.3 on 2019-07-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0005_auto_20190706_0226'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='showsourcefeed',
            name='feed_source',
        ),
    ]
