# Generated by Django 2.2.3 on 2019-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0006_auto_20190706_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='target_date',
            field=models.DateTimeField(db_index=True, verbose_name='Target Date'),
        ),
    ]
