# Generated by Django 2.2.3 on 2019-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0007_auto_20190711_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='episode_number',
            field=models.SmallIntegerField(blank=True, db_index=True, default=-1, null=True, verbose_name='Episode Number'),
        ),
        migrations.AddField(
            model_name='post',
            name='running_total',
            field=models.SmallIntegerField(blank=True, db_index=True, default=-1, null=True, verbose_name='Running Total'),
        ),
    ]
