# Generated by Django 2.2.3 on 2019-07-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0008_auto_20190712_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='total_shows',
            field=models.SmallIntegerField(blank=True, default=-1, null=True, verbose_name='Total Shows'),
        ),
    ]
