# Generated by Django 3.0.2 on 2020-02-16 08:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0009_show_total_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pakguru_app.Show'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Tags'), blank=True, db_index=True, null=True, size=None),
        ),
    ]
