# Generated by Django 3.0.2 on 2020-02-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0010_auto_20200216_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsourcefeed',
            name='feed_frequency',
            field=models.CharField(choices=[('ONE_TIME', 'once'), ('DAILY', 'Daily')], default='ONE_TIME', max_length=20, verbose_name='Feed Frequency'),
        ),
        migrations.AlterField(
            model_name='post',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Flagged'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Joke',
            field=models.BooleanField(default=False, verbose_name='Is Joke'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Politics',
            field=models.BooleanField(default=False, verbose_name='Is Political'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Quote',
            field=models.BooleanField(default=False, verbose_name='Is Quote'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_Show',
            field=models.BooleanField(default=True, verbose_name='Is Show'),
        ),
    ]
