# Generated by Django 3.0.2 on 2020-02-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakguru_app', '0011_auto_20200216_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsourcefeed',
            name='feed_frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('ON_DEMAND', 'On Demand'), ('DAILY', 'Daily'), ('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], default='ONE_TIME', max_length=20, verbose_name='Feed Frequency'),
        ),
    ]
