# Generated by Django 2.2.3 on 2019-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showepisodereferenceinfo',
            options={'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='showreferenceinfo',
            options={'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterField(
            model_name='showepisodereferenceinfo',
            name='episode_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Episode Title'),
        ),
        migrations.AlterField(
            model_name='showepisodereferenceinfo',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showepisodereferenceinfo',
            name='series_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Series Title'),
        ),
    ]
